pyinstaller --noconfirm --onedir --windowed \
  --add-data "prompts;prompts" \
  --add-data "app/database/schema.sql;app/database" \
  --add-data "app/ui/views;app/ui/views" \
  --add-data "translations;translations" \
  --collect-all PySide6 \
  --collect-all mysql.connector \
  --collect-all pygments \
  --name "AI_Exam_Tutor" \
  main.py